import { experimental_evaluate as evaluate } from "ai";
import { NextResponse } from "next/server";
import { movies, CATALOG_VERSION } from "@/lib/movies";
import type { HardFilters } from "@/lib/types";

type Body={preferences?:string[]; secondPreferences?:string[]; mode?:"solo"|"duo"; filters?:HardFilters; excludedIds?:number[]};
function passes(movie:typeof movies[number], f:HardFilters){ return (!f.runtimeMax||movie.runtime<=f.runtimeMax)&&(!f.runtimeMin||movie.runtime>=f.runtimeMin)&&(!f.yearMin||movie.year>=f.yearMin)&&(!f.yearMax||movie.year<=f.yearMax)&&(!f.genre||movie.genres.includes(f.genre)); }
function stateFor(movie:typeof movies[number], preferences:string[]){ return {movie:{id:movie.id,title:movie.title,year:movie.year,runtime:movie.runtime,genres:movie.genres,overview:movie.overview,mood:movie.mood,pace:movie.pace,theme:movie.theme}, request:preferences.join(" → ")}; }
async function scoreMovie(movie:typeof movies[number], preferences:string[]){ const result=await evaluate({model:"typesafe-ai/jev",state:stateFor(movie,preferences),maxRetries:0,questions:{overall:{type:"score",criteria:["0 — poor fit","1 — weak fit","2 — partial fit","3 — good fit","4 — exceptional fit"],instructions:"How well does this movie satisfy the viewer's complete request? Consider the movie facts and curated mood, pace, and theme tags."},mood:{type:"score",criteria:["0 — mismatch","1 — weak","2 — partial","3 — good","4 — exceptional"],instructions:"How well does the movie's mood match the request?"},pace:{type:"score",criteria:["0 — mismatch","1 — weak","2 — partial","3 — good","4 — exceptional"],instructions:"How well does the movie's pacing match the request?"},theme:{type:"score",criteria:["0 — mismatch","1 — weak","2 — partial","3 — good","4 — exceptional"],instructions:"How well do the movie's themes match the request?"}}}); const a=result.answers as Record<string,{score:number}>; return {movieId:movie.id,overall:a.overall.score/4,mood:a.mood.score/4,pace:a.pace.score/4,theme:a.theme.score/4,eligible:true}; }
export async function POST(request:Request){ try { const body=(await request.json()) as Body; const preferences=(body.preferences??[]).filter(Boolean).slice(-8); const second=(body.secondPreferences??[]).filter(Boolean).slice(-8); const filters=body.filters??{}; const excluded=new Set(body.excludedIds??[]); const candidates=movies.filter(m=>!excluded.has(m.id)&&passes(m,filters)); if(!preferences.length&&!second.length) return NextResponse.json({requestId:crypto.randomUUID(),catalogVersion:CATALOG_VERSION,appliedFilters:filters,evaluations:[],rankedEligibleIds:[]}); if(!process.env.AI_GATEWAY_API_KEY) return NextResponse.json({error:"AI_GATEWAY_API_KEY is required to evaluate a mood."},{status:503}); const first=preferences.length?await Promise.all(candidates.map(m=>scoreMovie(m,preferences))):[]; const secondScores=body.mode==="duo"&&second.length?await Promise.all(candidates.map(m=>scoreMovie(m,second))):[]; const byId=new Map(secondScores.map(s=>[s.movieId,s])); const evaluations=first.map(s=>{const b=byId.get(s.movieId); if(!b)return {...s,eligible:s.overall>=.6}; const overall=Math.min(s.overall,b.overall); return {...s,overall,mood:Math.min(s.mood,b.mood),pace:Math.min(s.pace,b.pace),theme:Math.min(s.theme,b.theme),eligible:overall>=.6};}).sort((a,b)=>b.overall-a.overall); return NextResponse.json({requestId:crypto.randomUUID(),catalogVersion:CATALOG_VERSION,appliedFilters:filters,evaluations,rankedEligibleIds:evaluations.filter(x=>x.eligible).map(x=>x.movieId)}); } catch(error){ console.error(error); return NextResponse.json({error:"The evaluation could not be completed. Try again."},{status:500}); } }
