"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bookmark, Check, Copy, Heart, RotateCcw, Sparkles, X } from "lucide-react";
import Matter from "matter-js";
import { movies } from "@/lib/movies";
import type { HardFilters, Movie, MovieEvaluation, MoodSnapshot } from "@/lib/types";

const initialIds = movies.map(m=>m.id);
const emptySession={preferences:[] as string[],secondPreferences:[] as string[],mode:"solo" as "solo"|"duo",filters:{} as HardFilters,evaluations:{} as Record<number,MovieEvaluation>,shortlistedIds:[] as number[],pinnedIds:[] as number[],dismissedIds:[] as number[]};
function parseRuntime(text:string):HardFilters { const max=text.match(/(?:under|below|at most)\s*(\d+)\s*(?:min|minutes)?/i)?.[1]; const between=text.match(/between\s*(\d+)\s*(?:and|-)\s*(\d+)\s*minutes?/i); return between?{runtimeMin:Number(between[1]),runtimeMax:Number(between[2])}:max?{runtimeMax:Number(max)}:{}; }
function Poster({movie,x,y,angle,pinned,onPin,onSeen,onInfo,onMove}:{movie:Movie;x:number;y:number;angle:number;pinned:boolean;onPin:()=>void;onSeen:()=>void;onInfo:()=>void;onMove:(x:number,y:number)=>void}){ const [broken,setBroken]=useState(false); const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null); return <article className="poster" tabIndex={0} aria-label={`${movie.title}, ${movie.year}`} style={{left:x,top:y,transform:`rotate(${angle}deg)`}} onPointerDown={e=>{if((e.target as HTMLElement).closest("button"))return; drag.current={x:e.clientX,y:e.clientY,ox:x,oy:y}; e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;onMove(drag.current.ox+e.clientX-drag.current.x,drag.current.oy+e.clientY-drag.current.y);}} onPointerUp={()=>{drag.current=null;}}><div className="poster-actions"><button className="icon-btn" aria-label={pinned?"Unpin movie":"Pin movie"} onClick={onPin}>{pinned?<Heart size={14} fill="currentColor"/>:<Bookmark size={14}/>}</button><button className="icon-btn" aria-label="Seen it" onClick={onSeen}><Check size={14}/></button><button className="icon-btn" aria-label="Movie details" onClick={onInfo}><Sparkles size={14}/></button></div>{pinned&&<span className="pinned-ribbon">PINNED</span>}{movie.posterPath&&!broken?<img src={movie.posterPath} alt="" onError={()=>setBroken(true)}/>:<div className="poster-fallback"><strong>{movie.title}</strong><small>{movie.year} · {movie.runtime} min</small></div>}<div className="poster-info"><strong>{movie.title}</strong><span>{movie.year} · {movie.runtime} min</span></div></article> }
export default function Home(){
 const [session,setSession]=useState(emptySession); const [prompt,setPrompt]=useState(""); const [second,setSecond]=useState(""); const [filters,setFilters]=useState<HardFilters>({}); const [loading,setLoading]=useState(false); const [status,setStatus]=useState(""); const [detail,setDetail]=useState<Movie|null>(null); const [surprise,setSurprise]=useState<Movie|null>(null); const [undo,setUndo]=useState<number|null>(null); const [positions,setPositions]=useState<Record<number,{x:number;y:number;a:number}>>({}); const [reduced,setReduced]=useState(false); const stageRef=useRef<HTMLDivElement>(null); const engineRef=useRef<Matter.Engine|null>(null); const requestRef=useRef(0);
 const activeMovies=useMemo(()=>movies.filter(m=>!session.dismissedIds.includes(m.id)),[session.dismissedIds]);
 const shownIds=session.shortlistedIds.length?Array.from(new Set([...session.shortlistedIds,...session.pinnedIds])):initialIds;
 useEffect(()=>{ const saved=localStorage.getItem("reel-gravity-session"); const hash=location.hash.slice(1); try{ if(hash){const snap=JSON.parse(decodeURIComponent(atob(hash))) as MoodSnapshot; setSession(s=>({...s,preferences:snap.preferences,secondPreferences:snap.secondPreferences,mode:snap.mode,filters:snap.filters,shortlistedIds:snap.shortlistedIds,pinnedIds:snap.pinnedIds,dismissedIds:snap.dismissedIds})); setFilters(snap.filters);} else if(saved){setSession(JSON.parse(saved));} }catch{} const m=window.matchMedia("(prefers-reduced-motion: reduce)"); setReduced(m.matches); },[]);
 useEffect(()=>{localStorage.setItem("reel-gravity-session",JSON.stringify(session));},[session]);
 useEffect(()=>{ if(!stageRef.current)return; const rect=stageRef.current.getBoundingClientRect(); const init:Record<number,{x:number;y:number;a:number}>={}; shownIds.forEach((id,i)=>{init[id]={x:24+(i*71)%(Math.max(240,rect.width-170)),y:30+(i*43)%(Math.max(180,rect.height-240)),a:(i%7-3)*2};}); setPositions(p=>{const n={...init,...p}; return n;}); if(reduced)return; const engine=Matter.Engine.create({gravity:{x:0,y:.24}}); engineRef.current=engine; const bodies=shownIds.map((id,i)=>Matter.Bodies.rectangle(init[id]?.x??40,init[id]?.y??40,132,198,{label:String(id),restitution:.25,friction:.6})); Matter.World.add(engine.world,bodies); const runner=Matter.Runner.create(); Matter.Runner.run(runner,engine); const raf=()=>{const next:Record<number,{x:number;y:number;a:number}>={}; bodies.forEach(b=>{next[Number(b.label)]={x:b.position.x,y:b.position.y,a:b.angle*57.3};}); setPositions(p=>({...p,...next})); requestAnimationFrame(raf)}; const frame=requestAnimationFrame(raf); return()=>{cancelAnimationFrame(frame); Matter.Runner.stop(runner); Matter.Engine.clear(engine);}; // eslint-disable-next-line react-hooks/exhaustive-deps
 },[reduced]);
 const evaluate=useCallback(async()=>{ if(!prompt.trim()&&!second.trim()){setStatus("Add a mood before asking Jev to judge the heap.");return;} const id=++requestRef.current; setLoading(true); setStatus("Jev is weighing the heap…"); const nextFilters={...filters,...parseRuntime(prompt)}; setFilters(nextFilters); try{const res=await fetch("/api/evaluate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({preferences:[...session.preferences,prompt].filter(Boolean),secondPreferences:[...session.secondPreferences,second].filter(Boolean),mode:session.mode,filters:nextFilters,excludedIds:session.dismissedIds})}); const data=await res.json(); if(id!==requestRef.current)return; if(!res.ok)throw new Error(data.error); const evaluations=Object.fromEntries((data.evaluations as MovieEvaluation[]).map(e=>[e.movieId,e])); setSession(s=>({...s,preferences:prompt?[...s.preferences,prompt].slice(-8):s.preferences,secondPreferences:second?[...s.secondPreferences,second].slice(-8):s.secondPreferences,filters:nextFilters,evaluations,shortlistedIds:data.rankedEligibleIds.slice(0,6)})); setPrompt("");setSecond("");setStatus(`${data.rankedEligibleIds.length} films rose to the surface.`); }catch(e){if(id===requestRef.current)setStatus(e instanceof Error?e.message:"The evaluation failed. Try again.");}finally{if(id===requestRef.current)setLoading(false);} },[filters,prompt,second,session]);
 const clear=()=>{requestRef.current++;setSession(s=>({...emptySession,dismissedIds:s.dismissedIds}));setFilters({});setPrompt("");setSecond("");setStatus("The heap is clear. Your seen list remains in this session.");};
 const pin=(id:number)=>setSession(s=>({...s,pinnedIds:s.pinnedIds.includes(id)?s.pinnedIds.filter(x=>x!==id):[...s.pinnedIds,id]}));
 const seen=(id:number)=>{setSession(s=>({...s,dismissedIds:[...s.dismissedIds,id],pinnedIds:s.pinnedIds.filter(x=>x!==id),shortlistedIds:s.shortlistedIds.filter(x=>x!==id)}));setUndo(id);setTimeout(()=>setUndo(null),5000);};
 const restore=()=>{if(undo===null)return;setSession(s=>({...s,dismissedIds:s.dismissedIds.filter(x=>x!==undo)}));setUndo(null);};
 const share=()=>{const snap:MoodSnapshot={v:1,preferences:session.preferences,secondPreferences:session.secondPreferences,mode:session.mode,filters:session.filters,shortlistedIds:session.shortlistedIds,pinnedIds:session.pinnedIds,dismissedIds:session.dismissedIds}; const value=btoa(encodeURIComponent(JSON.stringify(snap))); history.replaceState(null,"",`#${value}`);navigator.clipboard?.writeText(location.href);setStatus("Mood link copied to your clipboard.");};
 const surpriseMe=()=>{const pool=activeMovies.filter(m=>session.shortlistedIds.includes(m.id)&&!session.pinnedIds.includes(m.id));setSurprise(pool[Math.floor(Math.random()*pool.length)]??null);};
 return <main className="app-shell"><header className="topbar"><div className="brand">reel<span>gravity</span></div><div className="eyebrow">Contextual film finding · 01</div></header><div className="content"><section className="hero"><div><div className="eyebrow">A physical recommendation engine</div><h1>Let the right films<br/><em>rise to you.</em></h1><p className="lede">Describe the night you want. Jev reads the mood, pace, and themes in your request, then the movies that fit pull themselves out of the heap.</p></div><div className="stat"><strong>{session.shortlistedIds.length||movies.length}</strong>{session.shortlistedIds.length?"films currently in orbit":"curated films in the catalog"}<br/><span className="sans">Posters keep their place as your taste changes.</span></div></section>
 <section className="controls" aria-label="Movie preferences"><div className="mode-row"><div className="input-wrap"><label htmlFor="prompt">Your mood</label><input id="prompt" type="text" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")evaluate()}} placeholder="Animated movies for a rainy Sunday…" /></div><div className="input-wrap" style={{display:session.mode==="duo"?"block":"none"}}><label htmlFor="second">Their mood</label><input id="second" type="text" value={second} onChange={e=>setSecond(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")evaluate()}} placeholder="Something hopeful, not too long…" /></div><button className={`btn ${session.mode==="duo"?"active":""}`} onClick={()=>setSession(s=>({...s,mode:s.mode==="solo"?"duo":"solo"}))}>{session.mode==="solo"?"Two-person night":"Two people"}</button><button className="btn primary" disabled={loading} onClick={evaluate}>{loading?"Weighing…":"Find my films"}</button></div><div className="filter-row"><span className="eyebrow" style={{marginRight:4}}>Hard filters</span><input aria-label="Minimum runtime" type="number" min="1" placeholder="Min min" value={filters.runtimeMin??""} onChange={e=>setFilters(f=>({...f,runtimeMin:e.target.value?Number(e.target.value):undefined}))} style={{width:100,padding:"11px 10px"}}/><input aria-label="Maximum runtime" type="number" min="1" placeholder="Max min" value={filters.runtimeMax??""} onChange={e=>setFilters(f=>({...f,runtimeMax:e.target.value?Number(e.target.value):undefined}))} style={{width:100,padding:"11px 10px"}}/><input aria-label="Minimum year" type="number" min="1900" placeholder="From year" value={filters.yearMin??""} onChange={e=>setFilters(f=>({...f,yearMin:e.target.value?Number(e.target.value):undefined}))} style={{width:105,padding:"11px 10px"}}/><select aria-label="Genre" value={filters.genre??""} onChange={e=>setFilters(f=>({...f,genre:e.target.value||undefined}))}><option value="">Any genre</option>{["Animation","Drama","Comedy","Action","Adventure","Science Fiction","Romance","Thriller","Family","Horror"].map(g=><option key={g}>{g}</option>)}</select><button className="btn ghost" onClick={clear}>Clear</button><button className="btn ghost" onClick={share}><Copy size={14}/> Share mood</button></div><div className={`status ${status.toLowerCase().includes("required")||status.toLowerCase().includes("failed")?"error":""}`} role="status">{status}</div></section>
 <div className="canvas-head"><h2>{session.shortlistedIds.length?"Your current orbit":"The heap"}</h2><div className="action-row"><button className="btn" disabled={!session.shortlistedIds.length} onClick={surpriseMe}><Sparkles size={14}/> Surprise me</button><span className="sans" style={{color:"#80776b",fontSize:11}}>Drag a poster · pin a favorite · flick when seen</span></div></div>
 <section className="stage" ref={stageRef} aria-label="Interactive movie poster canvas">{shownIds.filter(id=>activeMovies.some(m=>m.id===id)).map(id=>{const movie=movies.find(m=>m.id===id)!;const p=positions[id]??{x:20,y:20,a:0};return <Poster key={id} movie={movie} x={p.x} y={p.y} angle={p.a} pinned={session.pinnedIds.includes(id)} onMove={(x,y)=>setPositions(prev=>({...prev,[id]:{...p,x,y}}))} onPin={()=>pin(id)} onSeen={()=>seen(id)} onInfo={()=>setDetail(movie)}/>})}{!session.shortlistedIds.length&&<div className="empty-stage"><div><strong>Nothing has risen yet.</strong><span>Give the heap a feeling, a constraint, or a rainy Sunday.</span></div></div>}</section>
 {session.shortlistedIds.length>0&&<section className="results"><div style={{gridColumn:"1/-1",display:"flex",justifyContent:"space-between",alignItems:"end"}}><div><div className="eyebrow">Match breakdown</div><p className="sans" style={{margin:"5px 0 0",color:"#8d857b",fontSize:12}}>AI estimates based on your current request. Factual filters are checked against catalog metadata.</p></div></div>{session.shortlistedIds.map(id=>{const m=movies.find(x=>x.id===id);const e=session.evaluations[id];if(!m||!e)return null;return <div className="result-card" key={id}><img src={m.posterPath} alt=""/><h3>{m.title}</h3><p>{m.year} · {m.runtime} min · {m.genres.slice(0,2).join(" / ")}</p><div className="bar"><i style={{width:`${e.overall*100}%`}}/></div><p style={{marginTop:5}}>{Math.round(e.overall*100)}% overall fit</p></div>})}</section>}
 <p className="credits">Movie data and imagery supplied by <a href="https://www.themoviedb.org" target="_blank">TMDB</a>. ReelGravity is not endorsed or certified by TMDB. Jev fit scores are estimates, not guarantees.</p></div>
 {detail&&<div role="dialog" aria-modal="true" className="detail-overlay" onClick={()=>setDetail(null)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.76)",zIndex:30,display:"grid",placeItems:"center",padding:20}}><div onClick={e=>e.stopPropagation()} style={{maxWidth:520,width:"100%",background:"#211f1c",border:"1px solid #514537",padding:22,position:"relative"}}><button className="icon-btn" aria-label="Close details" onClick={()=>setDetail(null)} style={{position:"absolute",right:12,top:12}}><X size={16}/></button><div className="eyebrow">Movie detail</div><h2 style={{fontSize:"2.3rem",fontWeight:500,letterSpacing:"-.05em",margin:"10px 0"}}>{detail.title}</h2><p className="sans" style={{color:"#b8aea0",lineHeight:1.6}}>{detail.overview}</p><p className="sans" style={{color:"#8f867b",fontSize:12}}>{detail.year} · {detail.runtime} minutes · {detail.genres.join(" · ")}</p>{session.evaluations[detail.id]&&<div className="breakdown">{([["Mood",session.evaluations[detail.id].mood],["Pace",session.evaluations[detail.id].pace],["Theme",session.evaluations[detail.id].theme]] as [string,number][]).map(([label,value])=><label key={label}><span>{label} fit</span><span>{Math.round(value*100)}%</span><div className="bar" style={{width:"100%"}}><i style={{width:`${value*100}%`}}/></div></label>)}</div>}</div></div>}
 {surprise&&<div role="dialog" aria-modal="true" className="detail-overlay" onClick={()=>setSurprise(null)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.8)",zIndex:40,display:"grid",placeItems:"center",padding:20}}><div onClick={e=>e.stopPropagation()} style={{textAlign:"center",maxWidth:520}}><div className="eyebrow">Tonight’s spotlight</div><h2 style={{fontSize:"clamp(3rem,8vw,7rem)",fontWeight:500,letterSpacing:"-.08em",lineHeight:.9,margin:"15px 0"}}>{surprise.title}</h2><p style={{color:"#b8aea0"}}>{surprise.year} · {surprise.runtime} minutes</p><button className="btn primary" onClick={()=>setSurprise(null)}>Keep exploring</button></div></div>}
 {undo!==null&&<button className="btn primary" onClick={restore} style={{position:"fixed",bottom:22,left:"50%",transform:"translateX(-50%)",zIndex:50}}><RotateCcw size={14}/> Undo seen it</button>}
 </main>
}
