import type { Movie } from "./types";
export const CATALOG_VERSION = "2026.09-curated";
const poster=(id:number)=>`https://image.tmdb.org/t/p/w342/${id}.jpg`;
export const movies:Movie[]=[
 {id:550,title:"Fight Club",year:1999,runtime:139,genres:["Drama"],overview:"An insomniac office worker crosses paths with a soap maker and forms an underground club.",posterPath:poster(550),mood:["dark","restless"],pace:["driving"],theme:["identity","rebellion"]},
 {id:11,title:"Star Wars",year:1977,runtime:121,genres:["Adventure","Science Fiction"],overview:"A farm boy joins a rebel mission against an authoritarian empire.",posterPath:poster(11),mood:["hopeful","adventurous"],pace:["propulsive"],theme:["heroism","freedom"]},
 {id:13,title:"Forrest Gump",year:1994,runtime:142,genres:["Drama","Romance"],overview:"A gentle man witnesses decades of American history while following his own path.",posterPath:poster(13),mood:["warm","bittersweet"],pace:["measured"],theme:["kindness","fate"]},
 {id:155,title:"The Dark Knight",year:2008,runtime:152,genres:["Drama","Action","Crime"],overview:"Batman faces a criminal mastermind who plunges Gotham into anarchy.",posterPath:poster(155),mood:["dark","intense"],pace:["propulsive"],theme:["justice","sacrifice"]},
 {id:157336,title:"Interstellar",year:2014,runtime:169,genres:["Science Fiction","Drama"],overview:"Explorers travel through a wormhole in space in humanity's search for a new home.",posterPath:poster(157336),mood:["awe-filled","melancholic"],pace:["expansive"],theme:["love","survival"]},
 {id:19995,title:"Avatar",year:2009,runtime:162,genres:["Action","Adventure","Fantasy"],overview:"A marine on an alien moon becomes torn between orders and a new world.",posterPath:poster(19995),mood:["wondrous","romantic"],pace:["sweeping"],theme:["nature","belonging"]},
 {id:920,title:"Cars",year:2006,runtime:117,genres:["Animation","Comedy","Family"],overview:"A hotshot race car learns that the road to victory is not always the fastest route.",posterPath:poster(920),mood:["sunny","playful"],pace:["brisk"],theme:["friendship","humility"]},
 {id:862,title:"Toy Story",year:1995,runtime:81,genres:["Animation","Comedy","Family"],overview:"A cowboy toy feels threatened when a flashy space ranger arrives in the playroom.",posterPath:poster(862),mood:["warm","playful"],pace:["brisk"],theme:["friendship","belonging"]},
 {id:508442,title:"Soul",year:2020,runtime:100,genres:["Animation","Drama","Family"],overview:"A musician gets a chance to return to life and discovers what makes it worth living.",posterPath:poster(508442),mood:["tender","reflective"],pace:["measured"],theme:["purpose","joy"]},
 {id:354912,title:"Coco",year:2017,runtime:105,genres:["Animation","Family","Music"],overview:"A young musician enters the land of the dead to uncover his family's history.",posterPath:poster(354912),mood:["vibrant","bittersweet"],pace:["brisk"],theme:["memory","family"]},
 {id:129,title:"Spirited Away",year:2001,runtime:125,genres:["Animation","Fantasy"],overview:"A girl enters a world ruled by gods, witches, and spirits where humans are changed.",posterPath:poster(129),mood:["dreamlike","strange"],pace:["wandering"],theme:["courage","identity"]},
 {id:207703,title:"Kingsman: The Secret Service",year:2014,runtime:129,genres:["Action","Comedy"],overview:"A street kid is recruited into a secret spy organization.",posterPath:poster(207703),mood:["playful","stylish"],pace:["kinetic"],theme:["class","loyalty"]},
 {id:497,title:"The Green Mile",year:1999,runtime:189,genres:["Drama","Fantasy"],overview:"A death row guard encounters a gentle giant with a mysterious gift.",posterPath:poster(497),mood:["sad","tender"],pace:["measured"],theme:["mercy","injustice"]},
 {id:680,title:"Pulp Fiction",year:1994,runtime:154,genres:["Crime","Thriller"],overview:"A series of connected stories unfolds in the Los Angeles underworld.",posterPath:poster(680),mood:["witty","dark"],pace:["rhythmic"],theme:["chance","violence"]},
 {id:603,title:"The Matrix",year:1999,runtime:136,genres:["Action","Science Fiction"],overview:"A hacker learns that reality is a simulated system and joins the fight to free humanity.",posterPath:poster(603),mood:["cool","urgent"],pace:["kinetic"],theme:["choice","reality"]},
 {id:6800,title:"The Shawshank Redemption",year:1994,runtime:142,genres:["Drama"],overview:"Two imprisoned men build a friendship that becomes a quiet act of hope.",posterPath:poster(278),mood:["hopeful","patient"],pace:["measured"],theme:["freedom","friendship"]},
 {id:694,title:"The Shining",year:1980,runtime:146,genres:["Horror","Thriller"],overview:"A family heads to an isolated hotel where a sinister presence waits.",posterPath:poster(694),mood:["dreadful","cold"],pace:["slow-burn"],theme:["isolation","madness"]},
 {id:597,title:"Titanic",year:1997,runtime:194,genres:["Drama","Romance"],overview:"A young aristocrat falls for an artist aboard a doomed ocean liner.",posterPath:poster(597),mood:["romantic","epic"],pace:["sweeping"],theme:["class","sacrifice"]},
 {id:120467,title:"The Grand Budapest Hotel",year:2014,runtime:100,genres:["Comedy","Drama"],overview:"A concierge and his lobby boy become embroiled in a stolen painting and family fortune.",posterPath:poster(120467),mood:["whimsical","melancholic"],pace:["brisk"],theme:["loyalty","civilization"]},
 {id:603692,title:"John Wick: Chapter 4",year:2023,runtime:169,genres:["Action","Thriller"],overview:"John Wick uncovers a path to defeating the High Table, but must fight his way free.",posterPath:poster(603692),mood:["stylish","relentless"],pace:["kinetic"],theme:["honor","revenge"]},
 {id:372058,title:"Your Name.",year:2016,runtime:106,genres:["Animation","Romance","Fantasy"],overview:"Two strangers find themselves mysteriously linked across time and distance.",posterPath:poster(372058),mood:["dreamlike","romantic"],pace:["brisk"],theme:["connection","fate"]},
 {id:438631,title:"Dune",year:2021,runtime:155,genres:["Science Fiction","Adventure"],overview:"The heir to a noble family is drawn into a war for a desert planet's future.",posterPath:poster(438631),mood:["majestic","tense"],pace:["deliberate"],theme:["power","destiny"]},
 {id:389,title:"12 Angry Men",year:1957,runtime:97,genres:["Drama"],overview:"A dissenting juror forces a panel to reconsider the evidence in a murder trial.",posterPath:poster(389),mood:["tense","thoughtful"],pace:["rising"],theme:["truth","justice"]},
 {id:497698,title:"Black Panther",year:2018,runtime:134,genres:["Action","Adventure"],overview:"A new king must protect his nation while facing a challenger from his family's past.",posterPath:poster(497698),mood:["bold","uplifting"],pace:["propulsive"],theme:["heritage","responsibility"]},
 {id:634649,title:"Spider-Man: No Way Home",year:2021,runtime:148,genres:["Action","Adventure","Fantasy"],overview:"A spell gone wrong brings familiar enemies and a new lesson in responsibility.",posterPath:poster(634649),mood:["exciting","bittersweet"],pace:["propulsive"],theme:["responsibility","loss"]}
];
export function getMovie(id:number){ return movies.find(movie=>movie.id===id); }
